### ISSUE TITLE
Unable to add a feature project and updatesite project in the repo

### ISSUE THREAD

**Issue by ogattaz** [alostale/luna-java-formatter#5]
As the PDE LunaJavaFormatter project is localized at the root of the repo, it isn't possible to add specialized projects to build the feature and the update site.

I forked your repo to purpose you a pull request but I can't.

Note: the availability of an update site is important for the Eclipse user on MacOs , the "dropin" folder isn't easily accessible...

**Comment by isaki** [comment]
Closing old ticket. This project is no longer maintained by its owner and is only receiving fixes so that it continues to function by those of us who can spare the time. If convenience is what you are looking for, you should move to the new eclipse formatter (as you will have less issues) or another commercially support plugin, such as Google's code formatter. This project is on life-support at best.
